Repository syncthing/syncthing-android, pull requests merged in 2018-06, with the labels that each got.

#1112 Fix Lint - 109 issues before, 40 issues after
  app/lint.xml
  app/src/main/java/com/nutomic/syncthingandroid/activities/WebGuiActivity.java
  app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingRunnable.java
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-ca-rES/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-in/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
Labels: build

#1114 Cache available debug facilities and fall back to hardcoded list (fixes #1113 #504)
  app/src/main/java/com/nutomic/syncthingandroid/http/GetRequest.java
  app/src/main/java/com/nutomic/syncthingandroid/service/Constants.java
  app/src/main/java/com/nutomic/syncthingandroid/service/RestApi.java
  app/src/main/java/com/nutomic/syncthingandroid/views/SttracePreference.java
Labels: enhancement

#1117 Handle revoked storage permission gracefully (fixes #871 #1115 #1116)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nutomic/syncthingandroid/activities/FirstStartActivity.java
  app/src/main/java/com/nutomic/syncthingandroid/activities/MainActivity.java
  app/src/main/java/com/nutomic/syncthingandroid/service/DeviceStateHolder.java
  app/src/main/java/com/nutomic/syncthingandroid/service/NotificationHandler.java
  app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java
  app/src/main/res/values/strings.xml
Labels: bug

#1119 Refactor SyncthingService (lifecycle), DeviceStateHolder, RestApi, multiple fixes
  app/src/main/java/com/nutomic/syncthingandroid/activities/DeviceActivity.java
  app/src/main/java/com/nutomic/syncthingandroid/activities/FirstStartActivity.java
  app/src/main/java/com/nutomic/syncthingandroid/activities/FolderActivity.java
  app/src/main/java/com/nutomic/syncthingandroid/activities/FolderPickerActivity.java
  app/src/main/java/com/nutomic/syncthingandroid/activities/MainActivity.java
  app/src/main/java/com/nutomic/syncthingandroid/activities/SettingsActivity.java
  app/src/main/java/com/nutomic/syncthingandroid/activities/ShareActivity.java
  app/src/main/java/com/nutomic/syncthingandroid/activities/StateDialogActivity.java
  app/src/main/java/com/nutomic/syncthingandroid/activities/WebGuiActivity.java
  app/src/main/java/com/nutomic/syncthingandroid/fragments/DeviceListFragment.java
  app/src/main/java/com/nutomic/syncthingandroid/fragments/DrawerFragment.java
  app/src/main/java/com/nutomic/syncthingandroid/fragments/FolderListFragment.java
  app/src/main/java/com/nutomic/syncthingandroid/http/ApiRequest.java
  app/src/main/java/com/nutomic/syncthingandroid/http/PollWebGuiAvailableTask.java
  app/src/main/java/com/nutomic/syncthingandroid/receiver/NetworkReceiver.java
  app/src/main/java/com/nutomic/syncthingandroid/service/DeviceStateHolder.java
  app/src/main/java/com/nutomic/syncthingandroid/service/EventProcessor.java
  app/src/main/java/com/nutomic/syncthingandroid/service/NotificationHandler.java
  app/src/main/java/com/nutomic/syncthingandroid/service/ReceiverManager.java
  app/src/main/java/com/nutomic/syncthingandroid/service/RestApi.java
  app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingRunnable.java
  app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java
Labels: bug

#1130 fix lint "unused quantity translations"
  app/lint.xml
Labels: build

#1134 Rename sttrace pref to debug_facilities_enabled (fixes #1133)
  app/src/main/java/com/nutomic/syncthingandroid/activities/SettingsActivity.java
  app/src/main/java/com/nutomic/syncthingandroid/service/Constants.java
  app/src/main/java/com/nutomic/syncthingandroid/service/RestApi.java
  app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingRunnable.java
  app/src/main/java/com/nutomic/syncthingandroid/views/SttracePreference.java
  app/src/main/res/xml/app_settings.xml
Labels: bug

#1140 Fix static leak in ShareActivity#CopyFilesTask
  app/src/main/java/com/nutomic/syncthingandroid/activities/ShareActivity.java
Labels: enhancement

#1141 Fix static leak in SettingsActivity#TestRootTask
  app/src/main/java/com/nutomic/syncthingandroid/activities/SettingsActivity.java
Labels: enhancement

#1136 Rename sttrace_cache variable
  app/src/main/java/com/nutomic/syncthingandroid/service/Constants.java
Labels: migration

#1137 Fix leak in SyncthingService.StartupTask (fixes #1135)
  app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java
Labels: enhancement

#1142 Fix static leak in LogActivity#AsyncTask
  app/src/main/java/com/nutomic/syncthingandroid/activities/LogActivity.java
Labels: enhancement

#1151 Fix ClassCastException in SyncthingService onCreate (fixes #1150)
  app/src/main/java/com/nutomic/syncthingandroid/activities/FolderPickerActivity.java
  app/src/main/java/com/nutomic/syncthingandroid/activities/MainActivity.java
  app/src/main/java/com/nutomic/syncthingandroid/activities/SyncthingActivity.java
  app/src/main/java/com/nutomic/syncthingandroid/activities/WebGuiActivity.java
  app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java
Labels: bug

#1149 Fix NPE in DrawerFragment if syncthing is terminated (fixes #1148)
  app/src/main/java/com/nutomic/syncthingandroid/fragments/DrawerFragment.java
Labels: bug

#1153 fix NPE during FolderActivity#addDeviceViewAndSetListener (fixes #1152)
  app/src/main/java/com/nutomic/syncthingandroid/activities/FolderActivity.java
Labels: bug

#1158 Rename RestApi.restart to RestApi.saveConfigAndRestart
  app/src/main/java/com/nutomic/syncthingandroid/activities/MainActivity.java
  app/src/main/java/com/nutomic/syncthingandroid/activities/SettingsActivity.java
  app/src/main/java/com/nutomic/syncthingandroid/service/RestApi.java
Labels: enhancement

#1157 Show meaningful error message if config file is missing (fixes #1156)
  app/src/main/java/com/nutomic/syncthingandroid/activities/WebGuiActivity.java
  app/src/main/res/values/strings.xml
Labels: bug

#1161 Add randomization to default camera folder name (fixes #1159)
  app/src/main/java/com/nutomic/syncthingandroid/util/ConfigXml.java
Labels: enhancement

#1163 Create or restore fragments before setAdapter is called (fixes #1162)
  app/src/main/java/com/nutomic/syncthingandroid/activities/MainActivity.java
Labels: bug

#1155 Fix multiple chances of a usage reporting dialog NPE (fixes #1154)
  app/src/main/java/com/nutomic/syncthingandroid/activities/MainActivity.java
  app/src/main/java/com/nutomic/syncthingandroid/service/RestApi.java
Labels: bug

#1166 Fix warning about missing write perm in root mode (fixes #1165)
  app/src/main/java/com/nutomic/syncthingandroid/activities/FolderPickerActivity.java
Labels: bug

#1175 Remove duplicate line in FolderPickerActivity
  app/src/main/java/com/nutomic/syncthingandroid/activities/FolderPickerActivity.java
Labels: bug
